name: todo_plus
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  intl: ^0.18.0
  flutter_datetime_picker: ^1.5.1
  animate_do: ^3.0.2
  flutter_beautiful_popup: ^1.7.0
  panara_dialogs: ^0.1.4
  lottie: ^1.4.2
  ftoast: ^2.0.0
  flutter_slider_drawer: ^2.1.3
  persian_datetime_picker: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/pic.jpg
    - assets/lottie/

